annotations:
  io.giantswarm.application.team: cabbage
  io.giantswarm.application.audience: "all"
apiVersion: v2
appVersion: 1.13.2
description: A Helm chart for CoreDNS
home: https://github.com/giantswarm/coredns-app
icon: https://s.giantswarm.io/app-icons/coredns/1/dark.svg
name: coredns-app
version: 1.28.3
